UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA WHERE TRGKHOA IS NOT NULL)

UPDATE HOCVIEN
SET DIEMTB = (
    SELECT AVG(DIEM)
    FROM (
        SELECT MAHV, MAMH, DIEM
        FROM KETQUATHI k1
        WHERE LANTHI = (
            SELECT MAX(LANTHI)
            FROM KETQUATHI k2
            WHERE k1.MAHV = k2.MAHV AND k1.MAMH = k2.MAMH
        )
    ) AS LastAttempts
    WHERE LastAttempts.MAHV = HOCVIEN.MAHV
)
WHERE EXISTS (
    SELECT 1
    FROM KETQUATHI
    WHERE MAHV = HOCVIEN.MAHV
);

UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN (
    SELECT MAHV
    FROM KETQUATHI
    WHERE LANTHI = 3 AND DIEM < 5
)

UPDATE HOCVIEN
SET XEPLOAI = 
    CASE 
        WHEN DIEMTB >= 9 THEN 'XS'
        WHEN DIEMTB >= 8 THEN 'G'
        WHEN DIEMTB >= 6.5 THEN 'K'
        WHEN DIEMTB >= 5 THEN 'TB'
        ELSE 'Y'
    END