SELECT MAHV, HO, TEN 
FROM HOCVIEN
WHERE YEAR(GETDATE()) - YEAR(NGSINH) >= 18;

SELECT MAGV, MAMH, HOCKY, NAM
FROM GIANGDAY
WHERE TUNGAY < DENNGAY;

SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE DATEDIFF(YEAR, NGSINH, NGVL) >= 22;

SELECT MAMH, TENMH
FROM MONHOC
WHERE ABS(TCLT - TCTH) <= 3;


