ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GIOITINH CHECK (GIOITINH IN ('Nam', 'Nu'));
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_GIOITINH CHECK (GIOITINH IN ('Nam', 'Nu'));

ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DIEM CHECK (DIEM BETWEEN 0 AND 10),
    CONSTRAINT CK_LANTHI CHECK (LANTHI BETWEEN 1 AND 3);

ALTER TABLE KETQUATHI
ADD KETQUATHI AS CASE WHEN DIEM >= 5 THEN 'Dat' ELSE 'Khong dat' END;

ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HOCKY CHECK (HOCKY BETWEEN 1 AND 3);

ALTER TABLE GIAOVIEN
ADD HOCVI varchar(20);
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));