ALTER TABLE SANPHAM
ADD GHICHU varchar(20);

ALTER TABLE KHACHHANG
ADD LOAIKH tinyint;

ALTER TABLE SANPHAM
ALTER COLUMN GHICHU varchar(100);

ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20);
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_LOAIKH CHECK (LOAIKH IN ('Vang lai', 'Thuong xuyen', 'Vip'));

ALTER TABLE SANPHAM 
ADD CONSTRAINT CK_DVT CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

ALTER TABLE SANPHAM 
ADD CONSTRAINT CK_GIA CHECK (GIA >= 500);

ALTER TABLE CTHD 
ADD CONSTRAINT CK_SL_LONHON_0 CHECK (SL > 0);

ALTER TABLE KHACHHANG 
ADD CONSTRAINT CK_NGDK CHECK (NGDK > NGSINH);