SELECT DISTINCT gv.HOTEN
FROM GIAOVIEN gv
JOIN GIANGDAY gd ON gv.MAGV = gd.MAGV
WHERE gd.MAMH = 'CTRR' 
AND gd.NAM = 2006 
AND gd.HOCKY = 1
AND gd.MAGV IN (
    SELECT MAGV 
    FROM GIANGDAY
    WHERE MALOP IN ('K11', 'K12')
    AND MAMH = 'CTRR'
    AND NAM = 2006
    AND HOCKY = 1
    GROUP BY MAGV
    HAVING COUNT(DISTINCT MALOP) = 2
);

SELECT hv.MAHV, hv.HO, hv.TEN
FROM HOCVIEN hv
JOIN KETQUATHI kq ON hv.MAHV = kq.MAHV
WHERE kq.MAMH = 'CSDL' 
AND kq.LANTHI = 1 
AND kq.KQUA = 'Khong Dat'
AND NOT EXISTS (
    SELECT * 
    FROM KETQUATHI kq2
    WHERE kq2.MAHV = hv.MAHV 
    AND kq2.MAMH = 'CSDL' 
    AND kq2.LANTHI > 1
);

SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV NOT IN (SELECT DISTINCT MAGV FROM GIANGDAY);

SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT 1
    FROM GIANGDAY GD
    JOIN MONHOC MH ON MH.MAMH = GD.MAMH
    WHERE GD.MAGV = GV.MAGV
    AND MH.MAKHOA = GV.MAKHOA
);

SELECT DISTINCT hv.HO, hv.TEN
FROM HOCVIEN hv
LEFT JOIN KETQUATHI kq ON hv.MAHV = kq.MAHV
WHERE hv.MALOP = 'K11' AND (
    EXISTS (
        SELECT * 
        FROM KETQUATHI kq1 
        WHERE kq1.MAHV = hv.MAHV 
        GROUP BY MAMH 
        HAVING COUNT(*) > 3 AND MAX(KQUA) = 'Khong Dat'
    )
    OR EXISTS (
        SELECT * 
        FROM KETQUATHI kq2 
        WHERE kq2.MAHV = hv.MAHV 
        AND kq2.MAMH = 'CTRR' 
        AND kq2.LANTHI = 2 
        AND kq2.DIEM = 5
    )
);

SELECT DISTINCT gv.HOTEN
FROM GIAOVIEN gv
JOIN GIANGDAY gd ON gv.MAGV = gd.MAGV
WHERE gd.MAMH = 'CTRR'
AND EXISTS (
    SELECT *
    FROM GIANGDAY gd2
    WHERE gd2.MAGV = gv.MAGV
    AND gd2.MAMH = 'CTRR'
    AND gd2.NAM = gd.NAM
    AND gd2.HOCKY = gd.HOCKY
    GROUP BY gd2.NAM, gd2.HOCKY
    HAVING COUNT(DISTINCT gd2.MALOP) >= 2
);

SELECT hv.MAHV, hv.HO, hv.TEN, kq.DIEM
FROM HOCVIEN hv
LEFT JOIN (
    SELECT kq1.MAHV, kq1.DIEM
    FROM KETQUATHI kq1
    JOIN (
        SELECT MAHV, MAX(LANTHI) as MaxLanThi
        FROM KETQUATHI
        WHERE MAMH = 'CSDL'
        GROUP BY MAHV
    ) kq2 ON kq1.MAHV = kq2.MAHV 
    AND kq1.LANTHI = kq2.MaxLanThi
    WHERE kq1.MAMH = 'CSDL'
) kq ON hv.MAHV = kq.MAHV;

SELECT hv.MAHV, hv.HO, hv.TEN, 
       MAX(kq.DIEM) as DIEM_CAO_NHAT
FROM HOCVIEN hv
LEFT JOIN KETQUATHI kq ON hv.MAHV = kq.MAHV
WHERE kq.MAMH = 'CSDL'
GROUP BY hv.MAHV, hv.HO, hv.TEN;