SELECT DISTINCT MH.TENMH
FROM MONHOC MH
JOIN GIANGDAY GD ON GD.MAMH = MH.MAMH
JOIN GIAOVIEN GV ON GV.MAGV = GD.MAGV
WHERE GV.HOTEN = 'Tran Tam Thanh'
AND GD.HOCKY = 1 AND GD.NAM = 2006

SELECT DISTINCT MH.MAMH, MH.TENMH
FROM MONHOC MH
JOIN GIANGDAY GD ON GD.MAMH = MH.MAMH
JOIN LOP L ON L.MAGVCN = GD.MAGV
WHERE L.MALOP = 'K11'
AND GD.HOCKY = 1 AND GD.NAM = 2006

SELECT HV.HO + ' ' + HV.TEN AS HOTEN
FROM LOP L
JOIN HOCVIEN HV ON L.TRGLOP = HV.MAHV
JOIN GIANGDAY GD ON L.MALOP = GD.MALOP
JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
JOIN MONHOC MH ON GD.MAMH = MH.MAMH
WHERE GV.HOTEN = 'Nguyen To Lan' 
  AND MH.TENMH = 'Co So Du Lieu';

SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH
JOIN DIEUKIEN DK ON DK.MAMH_TRUOC = MH.MAMH
JOIN MONHOC MH2 ON MH2.MAMH = DK.MAMH
WHERE MH2.TENMH = 'Co So Du Lieu'

SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH
JOIN DIEUKIEN DK ON DK.MAMH = MH.MAMH
JOIN MONHOC MH2 ON MH2.MAMH = DK.MAMH_TRUOC
WHERE MH2.TENMH = 'Cau Truc Roi Rac'