SELECT MASP, TENSP 
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc';

SELECT MASP, TENSP 
FROM SANPHAM
WHERE DVT IN ('cay', 'quyen');

SELECT MASP, TENSP 
FROM SANPHAM
WHERE MASP LIKE 'B%01';

SELECT MASP, TENSP 
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA BETWEEN 30000 AND 40000;

SELECT MASP, TENSP 
FROM SANPHAM
WHERE (NUOCSX = 'Trung Quoc' OR NUOCSX = 'Thai Lan') AND GIA BETWEEN 30000 AND 40000;

SELECT SOHD, TRIGIA 
FROM HOADON
WHERE NGHD IN ('2007-01-01', '2007-01-02');

SELECT SOHD, TRIGIA 
FROM HOADON
WHERE NGHD BETWEEN '2007-01-01' AND '2007-01-31'
ORDER BY NGHD ASC, TRIGIA DESC;

SELECT DISTINCT KH.MAKH, KH.HOTEN 
FROM KHACHHANG KH
JOIN HOADON HD ON KH.MAKH = HD.MAKH
WHERE HD.NGHD = '2007-01-01';

SELECT HD.SOHD, HD.TRIGIA 
FROM HOADON HD
JOIN NhanVien NV ON HD.MANV = NV.MANV
WHERE NV.HOTEN = 'Nguyen Van B' AND HD.NGHD = '2006-10-28';

SELECT DISTINCT SP.MASP, SP.TENSP 
FROM SANPHAM SP
JOIN CTHD CT ON SP.MASP = CT.MASP
JOIN HoaDon HD ON CT.SOHD = HD.SOHD
JOIN KhachHang KH ON HD.MAKH = KH.MAKH
WHERE KH.HOTEN = 'Nguyen Van A' AND HD.NGHD BETWEEN '2006-10-01' AND '2006-10-31';

SELECT DISTINCT SOHD 
FROM CTHD
WHERE MASP IN ('BB01', 'BB02');

